name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy frontend
        run: |
          cd /home/dev/project/webstack-cicd-project

          git pull origin main

          cd frontend
          npm install
          npm run build

          pm2 delete frontend || true
          pm2 start "npx serve -s dist -l 5000" --name frontend
